spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./src/main/resources/db/testdb;DB_CLOSE_ON_EXIT=TRUE;MODE=PostgreSQL;
    username: sa
    password:
  sql:
    init:
      mode: always
      encoding: utf-8
  h2:
    console:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true